In [1]:
import numpy as np
import pandas as pd
from os import listdir
from os.path import isfile, join

In [2]:
pwd

'/Users/vishu/SJSU/cmpe255/TermProject/cmpe255-termproject'

In [3]:
all_subject_df = pd.DataFrame()

In [4]:
def load_datasets(folderpath):
    global all_subject_df
    
    files = [f for f in listdir(folderpath) if isfile(join(folderpath, f))]
    
    for file in files:
        subject_id = file.split('.')
        full_file_name = folderpath + '/' + str(file)
        print ("Loading dataset - {}".format(full_file_name))
        subject_df = pd.read_csv(full_file_name,sep = ' ', header=None)
        subject_df['subject_id'] = subject_id[0]
        all_subject_df = all_subject_df.append(subject_df, ignore_index=True, sort=False)

In [5]:
load_datasets("./dataset/Protocol") # Provide the folder path containing datasets

Loading dataset - ./dataset/Protocol/subject108.dat
Loading dataset - ./dataset/Protocol/subject109.dat
Loading dataset - ./dataset/Protocol/subject107.dat
Loading dataset - ./dataset/Protocol/subject106.dat
Loading dataset - ./dataset/Protocol/subject104.dat
Loading dataset - ./dataset/Protocol/subject105.dat
Loading dataset - ./dataset/Protocol/subject101.dat
Loading dataset - ./dataset/Protocol/subject102.dat
Loading dataset - ./dataset/Protocol/subject103.dat

In [6]:
all_subject_df.shape

(2872533, 55)

In [7]:
load_datasets("./dataset/Optional") # Provide the folder path containing datasets

Loading dataset - ./dataset/Optional/subject108.dat
Loading dataset - ./dataset/Optional/subject109.dat
Loading dataset - ./dataset/Optional/subject106.dat
Loading dataset - ./dataset/Optional/subject105.dat
Loading dataset - ./dataset/Optional/subject101.dat

In [8]:
all_subject_df.shape

(3850505, 55)

In [10]:
all_subject_df['subject_id'].value_counts()

subject101    695769
subject108    588443
subject105    529556
subject106    491780
subject102    447000
subject104    329576
subject107    313599
subject103    252833
subject109    201949
Name: subject_id, dtype: int64

In [11]:
all_subject_df.head()

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,subject_id
0,5.89,0,NaN,33.3125,-9.79760,-1.45670,1.014380,-9.70702,-1.60337,1.32098,...,0.010364,0.010731,-35.4550,38.3829,-17.9083,0.546211,0.370903,0.695334,0.283892,subject108
1,5.90,0,NaN,33.3125,-9.91204,-1.41822,0.974050,-9.78262,-1.60285,1.29085,...,-0.005926,-0.006704,-35.4508,38.2543,-17.7663,0.545806,0.370867,0.695680,0.283872,subject108
2,5.91,0,NaN,33.3125,-9.87531,-1.57027,0.975113,-9.78237,-1.57265,1.29079,...,-0.002265,0.014646,-35.6984,38.2688,-17.0580,0.545484,0.371607,0.695437,0.284117,subject108
3,5.92,0,NaN,33.3125,-9.72175,-1.60870,1.054520,-9.70677,-1.60334,1.35118,...,0.035314,0.010983,-34.9492,38.7447,-17.6233,0.545474,0.372077,0.694859,0.284935,subject108
4,5.93,0,NaN,33.3125,-9.79920,-1.49497,0.975999,-9.58657,-1.57408,1.27549,...,-0.001065,-0.000410,-35.2105,38.8857,-17.9080,0.545810,0.372349,0.694122,0.285732,subject108

In [14]:
all_subject_df.describe()

,Timestamp,ActivityID,HeartRate,IMU_Hand_temperature,IMU_Hand_3D-acc_16g_1,IMU_Hand_3D-acc_16g_2,IMU_Hand_3D-acc_16g_3,IMU_Hand_3D-acc_6g_1,IMU_Hand_3D-acc_6g_2,IMU_Hand_3D-acc_6g_3,...,IMU_Ankle_3D-gyroscope_1,IMU_Ankle_3D-gyroscope_2,IMU_Ankle_3D-gyroscope_3,IMU_Ankle_3D-magnetometer_1,IMU_Ankle_3D-magnetometer_2,IMU_Ankle_3D-magnetometer_3,IMU_Ankle_orientation_1,IMU_Ankle_orientation_2,IMU_Ankle_orientation_3,IMU_Ankle_orientation_4
count,3.850505e+06,3.850505e+06,351553.000000,3.836167e+06,3.836167e+06,3.836167e+06,3.836167e+06,3.836167e+06,3.836167e+06,3.836167e+06,...,3.836949e+06,3.836949e+06,3.836949e+06,3.836949e+06,3.836949e+06,3.836949e+06,3.836949e+06,3.836949e+06,3.836949e+06,3.836949e+06
mean,1.646636e+03,6.868323e+00,105.547129,3.273636e+01,-4.103132e+00,3.682527e+00,3.489940e+00,-4.024812e+00,3.679261e+00,3.674633e+00,...,7.514615e-03,-2.550657e-02,7.523516e-03,-3.188182e+01,1.659992e+00,1.727174e+01,4.304324e-01,-1.826566e-02,2.786428e-01,-4.194467e-02
std,1.077869e+03,6.882659e+00,26.416055,1.947065e+00,6.077534e+00,6.093761e+00,4.042875e+00,6.091977e+00,5.927740e+00,4.045377e+00,...,1.017105e+00,5.571188e-01,1.667495e+00,1.967533e+01,2.177866e+01,2.073795e+01,3.263793e-01,5.589320e-01,3.231336e-01,4.600539e-01
min,5.640000e+00,0.000000e+00,57.000000,2.450000e+01,-1.546090e+02,-1.073120e+02,-1.188460e+02,-6.148950e+01,-6.187640e+01,-6.193470e+01,...,-2.907750e+01,-1.812690e+01,-1.647420e+01,-1.728650e+02,-1.404600e+02,-1.523230e+02,-2.536280e-01,-9.568760e-01,-9.746290e-01,-9.972810e-01
25%,7.402900e+02,0.000000e+00,85.000000,3.162500e+01,-8.701235e+00,1.291060e+00,1.133600e+00,-8.606820e+00,1.284980e+00,1.339980e+00,...,-8.715310e-02,-5.639330e-02,-1.295880e-01,-4.297980e+01,-1.232260e+01,3.425020e+00,1.640020e-01,-6.217010e-01,0.000000e+00,-5.123300e-01
50%,1.495380e+03,4.000000e+00,102.000000,3.318750e+01,-4.402830e+00,3.683890e+00,3.212280e+00,-4.329800e+00,3.718820e+00,3.411500e+00,...,4.933160e-03,-3.692280e-03,-2.932360e-04,-3.286470e+01,6.708340e-01,1.872690e+01,3.367410e-01,0.000000e+00,2.374720e-01,0.000000e+00
75%,2.474060e+03,1.200000e+01,122.000000,3.412500e+01,1.594705e-01,7.033530e+00,6.452675e+00,2.542840e-01,7.042305e+00,6.705150e+00,...,6.627590e-02,5.507580e-02,4.525870e-02,-1.878320e+01,1.711100e+01,3.314790e+01,6.329390e-01,5.653910e-01,5.729700e-01,4.129080e-01
max,4.475630e+03,2.400000e+01,202.000000,3.550000e+01,1.060340e+02,1.576110e+02,1.577600e+02,6.237240e+01,6.225980e+01,6.194460e+01,...,2.447930e+01,1.358820e+01,1.935600e+01,9.752550e+01,1.233060e+02,1.469000e+02,1.000000e+00,9.595380e-01,9.923540e-01,9.961050e-01

In [13]:
all_subject_df = all_subject_df.rename(index=str, columns={0: "Timestamp", 1: "ActivityID", 2: "HeartRate", 3:"IMU_Hand_temperature", 4:"IMU_Hand_3D-acc_16g_1", 5:"IMU_Hand_3D-acc_16g_2", 6:"IMU_Hand_3D-acc_16g_3", 7:"IMU_Hand_3D-acc_6g_1", 8:"IMU_Hand_3D-acc_6g_2", 9:"IMU_Hand_3D-acc_6g_3", 10:"IMU_Hand_3D-gyroscope_1", 11:"IMU_Hand_3D-gyroscope_2", 12:"IMU_Hand_3D-gyroscope_3", 13:"IMU_Hand_3D-magnetometer_1", 14:"IMU_Hand_3D-magnetometer_2", 15:"IMU_Hand_3D-magnetometer_3", 16:"IMU_Hand_orientation_1", 17:"IMU_Hand_orientation_2", 18:"IMU_Hand_orientation_3", 19:"IMU_Hand_orientation_4",20:"IMU_Chest_temperature", 21:"IMU_Chest_3D-acc_16g_1", 22:"IMU_Chest_3D-acc_16g_2", 23:"IMU_Chest_3D-acc_16g_3", 24:"IMU_Chest_3D-acc_6g_1", 25:"IMU_Chest_3D-acc_6g_2", 26:"IMU_Chest_3D-acc_6g_3", 27:"IMU_Chest_3D-gyroscope_1", 28:"IMU_Chest_3D-gyroscope_2", 29:"IMU_Chest_3D-gyroscope_3", 30:"IMU_Chest_3D-magnetometer_1", 31:"IMU_Chest_3D-magnetometer_2", 32:"IMU_Chest_3D-magnetometer_3", 33:"IMU_Chest_orientation_1", 34:"IMU_Chest_orientation_2", 35:"IMU_Chest_orientation_3", 36:"IMU_Chest_orientation_4",37:"IMU_Ankle_temperature", 38:"IMU_Ankle_3D-acc_16g_1", 39:"IMU_Ankle_3D-acc_16g_2", 40:"IMU_Ankle_3D-acc_16g_3", 41:"IMU_Ankle_3D-acc_6g_1", 42:"IMU_Ankle_3D-acc_6g_2", 43:"IMU_Ankle_3D-acc_6g_3", 44:"IMU_Ankle_3D-gyroscope_1", 45:"IMU_Ankle_3D-gyroscope_2", 46:"IMU_Ankle_3D-gyroscope_3", 47:"IMU_Ankle_3D-magnetometer_1", 48:"IMU_Ankle_3D-magnetometer_2", 49:"IMU_Ankle_3D-magnetometer_3", 50:"IMU_Ankle_orientation_1", 51:"IMU_Ankle_orientation_2", 52:"IMU_Ankle_orientation_3", 53:"IMU_Ankle_orientation_4"})

In [15]:
all_subject_df.head()

,Timestamp,ActivityID,HeartRate,IMU_Hand_temperature,IMU_Hand_3D-acc_16g_1,IMU_Hand_3D-acc_16g_2,IMU_Hand_3D-acc_16g_3,IMU_Hand_3D-acc_6g_1,IMU_Hand_3D-acc_6g_2,IMU_Hand_3D-acc_6g_3,...,IMU_Ankle_3D-gyroscope_2,IMU_Ankle_3D-gyroscope_3,IMU_Ankle_3D-magnetometer_1,IMU_Ankle_3D-magnetometer_2,IMU_Ankle_3D-magnetometer_3,IMU_Ankle_orientation_1,IMU_Ankle_orientation_2,IMU_Ankle_orientation_3,IMU_Ankle_orientation_4,subject_id
0,5.89,0,NaN,33.3125,-9.79760,-1.45670,1.014380,-9.70702,-1.60337,1.32098,...,0.010364,0.010731,-35.4550,38.3829,-17.9083,0.546211,0.370903,0.695334,0.283892,subject108
1,5.90,0,NaN,33.3125,-9.91204,-1.41822,0.974050,-9.78262,-1.60285,1.29085,...,-0.005926,-0.006704,-35.4508,38.2543,-17.7663,0.545806,0.370867,0.695680,0.283872,subject108
2,5.91,0,NaN,33.3125,-9.87531,-1.57027,0.975113,-9.78237,-1.57265,1.29079,...,-0.002265,0.014646,-35.6984,38.2688,-17.0580,0.545484,0.371607,0.695437,0.284117,subject108
3,5.92,0,NaN,33.3125,-9.72175,-1.60870,1.054520,-9.70677,-1.60334,1.35118,...,0.035314,0.010983,-34.9492,38.7447,-17.6233,0.545474,0.372077,0.694859,0.284935,subject108
4,5.93,0,NaN,33.3125,-9.79920,-1.49497,0.975999,-9.58657,-1.57408,1.27549,...,-0.001065,-0.000410,-35.2105,38.8857,-17.9080,0.545810,0.372349,0.694122,0.285732,subject108

In [16]:
all_subject_df = all_subject_df[all_subject_df['ActivityID'] != 0]

In [17]:
all_subject_df['ActivityID'].value_counts()

10    309935
4     238761
17    238690
1     192523
3     189931
7     188107
19    187188
2     185188
16    175353
6     164600
12    117216
13    104944
18     99878
5      98199
9      83646
11     54519
24     49360
20     46915
Name: ActivityID, dtype: int64

In [18]:
all_subject_df.describe()

,Timestamp,ActivityID,HeartRate,IMU_Hand_temperature,IMU_Hand_3D-acc_16g_1,IMU_Hand_3D-acc_16g_2,IMU_Hand_3D-acc_16g_3,IMU_Hand_3D-acc_6g_1,IMU_Hand_3D-acc_6g_2,IMU_Hand_3D-acc_6g_3,...,IMU_Ankle_3D-gyroscope_1,IMU_Ankle_3D-gyroscope_2,IMU_Ankle_3D-gyroscope_3,IMU_Ankle_3D-magnetometer_1,IMU_Ankle_3D-magnetometer_2,IMU_Ankle_3D-magnetometer_3,IMU_Ankle_orientation_1,IMU_Ankle_orientation_2,IMU_Ankle_orientation_3,IMU_Ankle_orientation_4
count,2.724953e+06,2.724953e+06,248827.000000,2.713085e+06,2.713085e+06,2.713085e+06,2.713085e+06,2.713085e+06,2.713085e+06,2.713085e+06,...,2.715086e+06,2.715086e+06,2.715086e+06,2.715086e+06,2.715086e+06,2.715086e+06,2.715086e+06,2.715086e+06,2.715086e+06,2.715086e+06
mean,1.529966e+03,9.705309e+00,102.699691,3.282060e+01,-3.749334e+00,3.635251e+00,3.983587e+00,-3.673006e+00,3.625672e+00,4.170947e+00,...,7.949872e-03,-2.538576e-02,7.383974e-03,-2.973949e+01,1.318131e+00,1.793508e+01,4.112081e-01,-6.099894e-02,2.686461e-01,-8.457543e-02
std,1.039252e+03,6.277255e+00,27.378507,1.897940e+00,6.307708e+00,6.581852e+00,4.218909e+00,6.321581e+00,6.363129e+00,4.214890e+00,...,1.048851e+00,5.833520e-01,1.771609e+00,1.932897e+01,2.188757e+01,2.043155e+01,3.254230e-01,5.619890e-01,3.306958e-01,4.655879e-01
min,3.120000e+01,1.000000e+00,57.000000,2.487500e+01,-1.546090e+02,-1.043010e+02,-1.188460e+02,-6.143160e+01,-6.187640e+01,-6.193470e+01,...,-2.907750e+01,-1.812690e+01,-1.647420e+01,-1.728650e+02,-1.404600e+02,-1.523230e+02,9.350400e-07,-9.568760e-01,-9.746290e-01,-9.972810e-01
25%,6.523200e+02,4.000000e+00,82.000000,3.181250e+01,-8.360530e+00,1.044210e+00,1.339950e+00,-8.262010e+00,1.043150e+00,1.557410e+00,...,-9.704220e-02,-5.997997e-02,-1.416770e-01,-4.084627e+01,-1.347980e+01,4.438193e+00,1.546613e-01,-6.626270e-01,0.000000e+00,-5.425788e-01
50%,1.302070e+03,1.000000e+01,97.000000,3.318750e+01,-3.322070e+00,3.624270e+00,3.950170e+00,-3.278330e+00,3.654470e+00,4.205020e+00,...,5.428515e-03,-3.512290e-03,3.140750e-04,-3.137340e+01,-3.416750e-01,1.983255e+01,2.898280e-01,0.000000e+00,2.325480e-01,0.000000e+00
75%,2.382700e+03,1.600000e+01,120.000000,3.418750e+01,3.289530e-01,6.931600e+00,7.069760e+00,3.986200e-01,6.911580e+00,7.288040e+00,...,7.242640e-02,6.240900e-02,5.058237e-02,-1.604850e+01,1.695120e+01,3.438148e+01,6.151050e-01,5.106850e-01,5.611708e-01,3.585940e-01
max,4.245680e+03,2.400000e+01,202.000000,3.550000e+01,1.060340e+02,1.576110e+02,1.577600e+02,6.237240e+01,6.225980e+01,6.192340e+01,...,2.447930e+01,1.358820e+01,1.935600e+01,9.155160e+01,9.424780e+01,1.469000e+02,1.000000e+00,9.595380e-01,9.668930e-01,9.961050e-01

In [19]:
all_subject_df.head()

,Timestamp,ActivityID,HeartRate,IMU_Hand_temperature,IMU_Hand_3D-acc_16g_1,IMU_Hand_3D-acc_16g_2,IMU_Hand_3D-acc_16g_3,IMU_Hand_3D-acc_6g_1,IMU_Hand_3D-acc_6g_2,IMU_Hand_3D-acc_6g_3,...,IMU_Ankle_3D-gyroscope_2,IMU_Ankle_3D-gyroscope_3,IMU_Ankle_3D-magnetometer_1,IMU_Ankle_3D-magnetometer_2,IMU_Ankle_3D-magnetometer_3,IMU_Ankle_orientation_1,IMU_Ankle_orientation_2,IMU_Ankle_orientation_3,IMU_Ankle_orientation_4,subject_id
6147,67.36,1,84.0,33.8125,-9.64938,-1.68584,0.978888,-9.46791,-1.68076,1.15480,...,-0.058976,0.001427,-34.9285,37.8429,-17.4803,0.551748,0.371357,0.693585,0.276781,subject108
6148,67.37,1,NaN,33.8125,-9.80348,-1.72328,0.899731,-9.46778,-1.74110,1.23043,...,0.020064,-0.008885,-34.9496,38.6152,-17.9068,0.551698,0.371484,0.693471,0.276996,subject108
6149,67.38,1,NaN,33.8125,-9.65232,-1.53509,0.862873,-9.46854,-1.75627,1.15496,...,0.020882,-0.019795,-35.5699,37.4857,-18.4750,0.551888,0.371094,0.693512,0.277036,subject108
6150,67.39,1,NaN,33.8125,-9.65045,-1.64823,0.940257,-9.49956,-1.78632,1.07956,...,-0.003075,-0.013015,-35.4679,38.7685,-18.3343,0.551830,0.371118,0.693494,0.277167,subject108
6151,67.40,1,NaN,33.8125,-9.54564,-1.53764,0.672043,-9.48260,-1.66553,1.18498,...,-0.009872,0.032670,-35.4625,38.5107,-18.3340,0.551878,0.371197,0.693445,0.277089,subject108

In [21]:
# Impute Heart Rate

def person_activity_mean(x):
    # compute mean() for a particular person and activity combination
    pass
    
# Need to use mean value for a particular activity for the particular subject
#new_df = all_subject_df['HeartRate'].fillna((all_subject_df['HeartRate'].apply(lambda x: person_activity_mean(x))))